### ISSUE TITLE
TypeError: Cannot redefine property: stack

### ISSUE THREAD

**Issue by SuficioAC** [InjectiveLabs/injective-ts#259]
Running a simple gRPC call using the TS SDK which errors results in the following error:

```
/home/services/injective/node_modules/@injectivelabs/exceptions/dist/cjs/exception.js:68
        super.stack = stack;
                    ^

TypeError: Cannot redefine property: stack
    at GrpcUnaryRequestException.setStack (/home/services/injective/node_modules/@injectivelabs/exceptions/dist/cjs/exception.js:68:21)
    at GrpcUnaryRequestException.parseError (/home/services/injective/node_modules/@injectivelabs/exceptions/dist/cjs/exception.js:39:14)
    at new ConcreteException (/home/services/injective/node_modules/@injectivelabs/exceptions/dist/cjs/exception.js:30:14)
    at new GrpcUnaryRequestException (/home/services/injective/node_modules/@injectivelabs/exceptions/dist/cjs/exceptions/GrpcUnaryRequestException.js:8:9)
    at IndexerGrpcDerivativesApi.<anonymous> (/home/services/injective/node_modules/@injectivelabs/sdk-ts/dist/cjs/client/indexer/grpc/IndexerGrpcDerivativesApi.js:200:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/services/injective/node_modules/@injectivelabs/sdk-ts/dist/cjs/client/indexer/grpc/IndexerGrpcDerivativesApi.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Occurs due to `Error.stack` not being overwritable.

Makes the TS SDK unusable without modifying the source.

Node v21.2.0

**Comment by zlace** [comment]
Facing this issue as well.

**Comment by bangjelkoski** [comment]
How can I reproduce?

**Comment by zlace** [comment]
Seems like it happens on node >20, resolved by fixing node version to 18. 

One quick way to reproduce is trying to send some funds off an empty wallet (to trigger rpc error).

**Comment by SuficioAC** [comment]
Yes, using a recent Node version, any error emitted by the library will cause this error.

**Comment by ahwlsqja** [comment]
Hi, I've been looking into this issue and I think I can help fix it.

The `TypeError: Cannot redefine property: stack` appears to be caused by defining `stack` as a non-configurable property via `Object.defineProperty` in the exception classes, which conflicts with the native `Error.stack` property behavior.

I'd like to submit a PR with:
1. A fix for the property redefinition issue
2. Unit tests for the exceptions package to prevent regressions

Would that be welcome? Happy to discuss the approach first if preferred.
