### ISSUE TITLE
 Invalid string. Length must be a multiple of 4

### ISSUE THREAD

**Issue by sajshuai** [InjectiveLabs/injective-ts#293]
use sendTokens and result get this error:
`Error: Invalid string. Length must be a multiple of 4
    at getLens (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/base64-js/index.js:26:11)
    at Object.toByteArray (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/base64-js/index.js:55:14)
    at fromBase64 (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/@injectivelabs/sdk-ts/node_modules/@cosmjs/encoding/build/base64.js:36:21)
    at decodeAttribute (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/@injectivelabs/sdk-ts/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:43:40)
    at Array.map (<anonymous>)
    at decodeAttributes (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/@injectivelabs/sdk-ts/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:48:53)
    at decodeEvent (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/@injectivelabs/sdk-ts/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:53:40)
    at Array.map (<anonymous>)
    at decodeEvents (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/@injectivelabs/sdk-ts/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:58:49)
    at decodeTxData (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/injmint/node_modules/@injectivelabs/sdk-ts/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:66:31)`

**Comment by sajshuai** [comment]
in mintscan can see transaction is success

**Comment by bangjelkoski** [comment]
You are passing an invalid string, as it states in the error, probably a Uint8Array or Base64 instead of Hex. This issue is unrelated to `injective-ts`, closing.

**Comment by sajshuai** [comment]
https://github.com/cosmos/cosmos-sdk/issues/11997
termint version problem

**Comment by zkvm** [comment]
> [cosmos/cosmos-sdk#11997](https://github.com/cosmos/cosmos-sdk/issues/11997) tendermint version problem

how to fix this? ser

**Comment by liuqiang1357** [comment]
I had the same problem.
